Submission Folder/LakshmanKishore.html
My first Pull Request for Hacktober fest!!!
=> Submitting Slack Clone

Submission Folder/submission_ishaan.html
[LINK](https://codedamn.com/project/solution/615831a5bd24a00009282320)
=> adding link

Submission Folder/submission_Sanket-Mathur.html
This is my submission for the Hacktoberfest challenge on codedamn.com
The template I've used is "Slack Clone"
=> Submission for Hacktoberfest challenge

Submission Folder/muhsin22.html
I am completed my project. Please take look at my work
=> Eventually - Stunning HTML5 Landing Page done

Submission Folder/subhayu99.html
👉   <b>Name of the file: </b> <i>subhayu99.html</i><br/>
👉   <b>Email ID: </b> <i>balasubhayu99@gmail.com</i><br/>
👉   <b>GitHub Username: </b> <i>subhayu99</i><br/>
👉   <b>Name: </b> <i>Subhayu Kumar Bala</i><br/>
=> Submission for Hulu clone project

Submission Folder/arnav1776.html
Astral Portfolio page by Arnav Sharma
=> Astral Portfolio Page

Submission Folder/nandirishav.html, Submission Folder/submission_nandirishav.html
Solution URL - https://codedamn.com/project/solution/615720d7dbe0bc0009e4bf4d
=> Hulu Clone Project

Submission Folder/Abhijay007.html, Submission Folder/submission_Abhijay007.html
Added codedamn project submission URL: https://codedamn.com/project/solution/6157da78bdeaf30009161fe2
=> Added codedamn project submission URL (Astral Portfolio Page)

Submission Folder/submission_Ankan002.html
Project Topic: Slack Clone
File Name: submission_Ankan002.html
=> Submission of slack clone from Ankan002

Submission Folder/Yash-Wasalwar-07.html
Hi there, this is Yash👋!
I have completed the Hulu clone project, learned a lot many new things while making this project!!
I kindly urge you to merge this pull request, if any changes do let me know, will edit that.
Thank you!
=> Hulu project completed !

Submission Folder/Eventually Landing Page/submission__khaftab.html
Reverts codedamn/codedamn-hacktoberfest-projects#36
Hi Khaftab,
In the PR,  you have uploaded the link in the folder. The folder isn't necessary, the link and other details is fine.
=> Revert "Submission of Eventually Landing Page"

Submission Folder/submission_Dev2212.html
Thank You For Organising this for beginners.
=> Created Hulu clone for codedamn-hacktoberfest! Yay! 🎉

Submission Folder/ishita1505.html
Completed a project on Codedamn website and submitted a pull request.
=> Created ishita1505.html

Submission Folder/yoursDaddy007.html
https://codedamn.com/project/solution/617394c939c6ad000983f109
=> yoursDaddy007.html for hacktoberfest submission

Submission Folder/Eventually Landing Page/submission_muhsinfazal.html
Could you please send me the Always be codin' shirt, if possible?  Really love it. 😄
=> Resubmission after necessary changes.

Submission Folder/Eventually Landing Page/submission_Izroth404.html
Submission for Eventually landing page created. Thanks and Regards
=> Create submission_Izroth404.html for Eventually Landing Page

Submission Folder/BasilVictor.html
GitHub Landing page submission on Codedamn.
=> GitHub Landing Page - BasilVictor

Submission Folder/submission_stutimongia2024.html
Submission Link: [https://codedamn.com/project/solution/616be45464155500099b8803](https://codedamn.com/project/solution/616be45464155500099b8803)
Email address: stubhi2024@gmail.com
Github Username: stutimongia2024
Name: Stuti Mongia
=> Submission of Multiverse Photo Gallery Project

Submission Folder/Hulu Clone Project/submission_soham117.html
=> Added Hulu clone 

Submission Folder/submission_manshadchangampalli.html
=> create my html file

Submission Folder/submission_KrishnaManmayi.html
=> Hacktoberfest submisssion

Submission Folder/Instagram /instagram-priyanshuSharma-WebDev.html
looking forward to merging my pull request @deepxcode
=> add markup and codedamn username

Submission Folder/submission_MahenoorAhsan(Hulu).html, Submission Folder/submission_MahenoorAhsan.html
Hulu clone using Html/Css  & javaScript
=> Hulu clone

Submission Folder/Submission_Apoorv266.html
The submission is made according to the given protocol. I hope you like the project.
=> HULU Clone For Codedamn Hacktoberfest

Submission Folder/submission_MoulinaPradhan.html
Submit project Disney clone project [React]
=> Submission Disney clone project [React]

Submission Folder/Instagram /insta-clone.html
add new file name insta-clone.html
=> Created Instagram clone using codedamn

Submission Folder/Hulu Clone Project/submission_tamojeetK.html
=> Created Hulu Clone📺📦

Submission Folder/submission_j4m3ee.html
now i add js fucntion to active btn
=> Submission Slack-clone by j4m3ee

Submission Folder/GitHub landing page Project/submission-Lakshit-Chiranjiv.html
Added a new folder for Github clone projects and also added my html file in that folder
=> Added submission-Lakshit-Chiranjiv.html file

Submission Folder/submission_arjun-710.html, Submission Folder/submisson_akash5256.html
=> submission of Instagram Clone

Submission Folder/Slack Project/submission_cp-Coder.html
Name of the file: submission_cp-Coder.html
Email ID: bt20mme002@students.vnit.ac.in
GitHub Username: cp-Coder
Name: Abhiuday Gupta
Codedamn's submission URL: [Solution](https://codedamn.com/project/solution/61596c668af4a90009defd15)
=> Slack-clone

Submission Folder/submission_tarunbisht-24.html
My pr is here please have a look on my submission and merge it.
=> My Project - Astral Portfolio Page

Submission Folder/Submission_Apoorv266.html, Submission Folder/submission_Shreya2803.html
Name of the file:Shreya2803.html
codedamn's submission URL:https://codedamn.com/project/solution/617ec65d1989360009e33bd0
codedamn username: @Shreya2803
Name: Shreya Som
EmailId :som.shreya3@gmail.com
=> submission_Shreya2803.html

Submission Folder/submission_Aryamanz29.html
- Submission URL : https://codedamn.com/project/solution/617ece145e2d6200082bb066
- Email ID : aryamanz29@gmail.com
- GitHub Username : Aryamanz29 (https://github.com/Aryamanz29)
- Codedamn Username : Aryaman @Aryamanz29 (https://codedamn.com/user/Aryamanz29)
- Name: Aryaman
=>  Submission : AryamanZ29 - Hulu Clone

Submission Folder/Instagram /VanshSh.html
=> Feat: Add Instagram Clone

Submission Folder/submission_realanupreet.html
Added the Astral portfolio project that i have made :]
=> added astral portfolio project

Submission Folder/wweverma1.html
This is Instagram clone developed during the Codedamn Hacktoberfest 2021 using HTML, CSS and JS
Submitted Project URL: https://codedamn.com/project/solution/617cf1d2cca40d00094bbcaa
[Aditya Verma](https://github.com/wweverma1) on 31st October, 2021.
=> Project Solution of Instagram Clone by Aditya Verma

Submission Folder/Submission_Codes5761.html
Created Slack Clone and Submission_Codes5761.html
=> Created Slack Clone and Submission_Codes5761.html

Submission Folder/Slack Clone Project
My second project Slack Clone Project
https://codedamn.com/project/solution/6159d622baef9a00085de9e5
Email- tushar78628@gmail.com
=> Created Slack Clone Project

Submission Folder/submission_mehraTushar.html
https://codedamn.com/project/solution/6159d622baef9a00085de9e5
Email- tushar78628@gmail.com
=> Slack Clone Project

Submission Folder/Disney clone project [React]/submission_SurendarSingh.html
Made a Disney Clone
Is the PR Valid?
and ready to merge?
If not do let me know what changes to make
I will do it 
Thank You
=> Disney Clone

Submission Folder/Hulu Clone Project/submission_Sagar-dev3.html
also added the details as instructed
=> Added hulu clone project link through html file

Submission Folder/Avinaba-Mazumdar.html
Made Disney+ Clone with React 18.
This is the participation project for Hacktoberfest 2021 at Codedamn.
=> Codedamn Disney+ Clone UI

Submission Folder/1Hanif1.html
Had a lot of fun building this. Especially coding my own carousel using Vanilla JS. it was tricky but I got it done hehe
=> Disney+ Clone 
